# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Set Gradle executable
      run: chmod +x gradlew
    - name: Compile Task-Tracker-Entities
      run: |
        cd Task-Tracker-Entities &&
        ln -s ../gradle &&
        ln -s ../gradlew &&
        ./gradlew check publishToMavenLocal
    - name: Compile Task-Tracker-Usecases
      run: |
        cd Task-Tracker-Usecases &&
        ln -s ../gradle &&
        ln -s ../gradlew &&
        ./gradlew check publishToMavenLocal
    - name: Compile Task-Tracker-Usecases-SQLite-Impl
      run: |
        cd Task-Tracker-Usecases-SQLite-Impl &&
        ln -s ../gradle &&
        ln -s ../gradlew &&
        ./gradlew check publishToMavenLocal
    - name: Compile Task-Tracker-Usecases-CLI
      run: |
        cd Task-Tracker-CLI &&
        ln -s ../gradle &&
        ln -s ../gradlew &&
        ./gradlew check assembleDist
    - uses: actions/upload-artifact@v3
      with:
        name: distribution
        path: ./Task-Tracker-CLI/build/distributions/*.zip
    - uses: actions/upload-artifact@v3
      with:
        name: packages
        path: ~/.m2/repository/app/tasktrackersystems
  build-windows:

    runs-on: windows-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: packages
        path: ~/.m2/repository/app/tasktrackersystems
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.4
    - name: Compile Task-Tracker-Usecases-GUI
      run: |
        cd Task-Tracker-GUI
        gradle wrapper
        .\gradlew.bat check packageReleaseMsi